name: t_utils
description: "A package that is full of widgets, helper methods and utilities"

version: 0.0.2


  # Follow the semantic versioning guidelines:
  #
  #  Major changes that break backward compatibility: 1.0.0 -> 2.0.0
  #  Minor changes: 1.0.0 -> 1.1.0
  #  Patches or bug fixes: 1.0.0 -> 1.0.1

homepage: https://github.com/CodingwithTea/t_utils
repository: https://github.com/CodingwithTea/t_utils
issue_tracker: https://github.com/CodingwithTea/t_utils/issues

  # Use in your project as defined below
  # T Packages
  # t_utils:
  #  git:
  #    url: https://github.com/CodingwithTea/t_utils.git
  #    ref: v0.0.4


environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


  get: ^4.6.6
  intl: ^0.19.0
  iconsax: ^0.0.8
  shimmer: ^3.0.0
  lottie: ^3.3.1
  clipboard: ^0.1.3
  get_storage: ^2.1.1
  url_launcher: ^6.3.1
  data_table_2: ^2.5.18
  dropdown_search: ^6.0.2

  flutter_quill: ^10.8.5
  flutter_dropzone: ^4.2.1
  flutter_colorpicker: ^1.1.0
  omni_datetime_picker: ^2.0.5
  multi_select_flutter: ^4.1.3
  animated_toggle_switch: ^0.8.4

  connectivity_plus: ^6.1.2
  device_info_plus: ^11.2.1
  country_code_picker: ^3.1.0
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/